baseURL: https://loonanchauvette.github.io/ 
title: Loonan Chauvette
paginate: 5
theme: charlolamode
# To build -> hugo -t charlolamode

languages:
  en:
    weight: 1
    languageName: English
    menu:
      main:
          - name: Home
            pageRef: home
            url: /
            weight: 10
          - name: Publications
            pageRef: publications
            url: /publications
            weight: 20
          - name: Articles
            pageRef: articles
            url: publications/articles
            weight: 25
            parent: Publications
          - name: Posters
            pageRef: posters
            url: publications/posters
            weight: 27
            parent: Publications
          - name: Contact
            pageRef: contact
            url: /contact
            weight: 30


    params:
      profileMode:  
          enabled: true 
          title: Hello, I am Loonan !
          description: |
            I am an audiologist and a PhD student.

            I work in auditory and multisensory perception.
          imageUrl: "/images/Round.png"
          imageTitle: profile image
          imageWidth: 180
          imageHeight: 180
          buttons:
              - name: My Lab
                url: https://www.facebook.com/MAPLabCERVO


  fr:
    weight: 2
    languageName: Français
    menu:
      main:
          - name: Accueil
            pageRef: home
            url: /
            weight: 10
          - name: Publications
            url: /publications
            weight: 20
          - name: Articles
            pageRef: articles
            url: publications/articles
            weight: 25
            parent: Publications
          - name: Affiches
            pageRef: affiches
            url: publications/posters
            weight: 27
            parent: Publications
          - name: Contactez-moi
            url: /contact
            weight: 30

    params:

      profileMode:  
          enabled: true 
          title: Bonjour, moi c'est Loonan !
          description: |
            Je suis audiologiste et étudiant au doctorat.

            Ma recherche porte sur la perception auditive et multisensorielle.
          imageUrl: "/images/Round.png"
          imageTitle: profile image
          imageWidth: 180
          imageHeight: 180
          buttons:
              - name: Mon Labo
                url: https://www.facebook.com/MAPLabCERVO


params:
    author: Loonan Chauvette
    defaultTheme: light
    disableThemeToggle: false
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowToc: false
    dateFormat: "2006-01-02"

    socialIcons:
        - name: googlescholar
          url: "https://scholar.google.com/citations?user=XvN-yIIAAAAJ&hl=en"
        - name: github
          url: "https://github.com/LoonanChauvette"
        - name: linkedin
          url: "https://www.linkedin.com/in/loonan-chauvette-50844a14b"

    assets:     # change favicon in images folder (icon for web tab)
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

